export type Country = { name: string; value: string; code: string };

export const PHONE_COUNTRIES: Country[] = [
  { name: 'Afghanistan', value: '+93', code: 'AF' },
  { name: 'Albania', value: '+355', code: 'AL' },
  { name: 'Algeria', value: '+213', code: 'DZ' },
  { name: 'Andorra', value: '+376', code: 'AD' },
  { name: 'Angola', value: '+244', code: 'AO' },
  { name: 'Argentina', value: '+54', code: 'AR' },
  { name: 'Armenia', value: '+374', code: 'AM' },
  { name: 'Australia', value: '+61', code: 'AU' },
  { name: 'Austria', value: '+43', code: 'AT' },
  { name: 'Azerbaijan', value: '+994', code: 'AZ' },
  { name: 'Bahrain', value: '+973', code: 'BH' },
  { name: 'Bangladesh', value: '+880', code: 'BD' },
  { name: 'Belgium', value: '+32', code: 'BE' },
  { name: 'Brazil', value: '+55', code: 'BR' },
  { name: 'Bulgaria', value: '+359', code: 'BG' },
  { name: 'Cambodia', value: '+855', code: 'KH' },
  { name: 'Cameroon', value: '+237', code: 'CM' },
  { name: 'Canada', value: '+1', code: 'CA' },
  { name: 'Chile', value: '+56', code: 'CL' },
  { name: 'China', value: '+86', code: 'CN' },
  { name: 'Colombia', value: '+57', code: 'CO' },
  { name: 'Costa Rica', value: '+506', code: 'CR' },
  { name: 'Croatia', value: '+385', code: 'HR' },
  { name: 'Czech Republic', value: '+420', code: 'CZ' },
  { name: 'Denmark', value: '+45', code: 'DK' },
  { name: 'Egypt', value: '+20', code: 'EG' },
  { name: 'Estonia', value: '+372', code: 'EE' },
  { name: 'Finland', value: '+358', code: 'FI' },
  { name: 'France', value: '+33', code: 'FR' },
  { name: 'Germany', value: '+49', code: 'DE' },
  { name: 'Greece', value: '+30', code: 'GR' },
  { name: 'Hong Kong', value: '+852', code: 'HK' },
  { name: 'Hungary', value: '+36', code: 'HU' },
  { name: 'Iceland', value: '+354', code: 'IS' },
  { name: 'India', value: '+91', code: 'IN' },
  { name: 'Indonesia', value: '+62', code: 'ID' },
  { name: 'Iran', value: '+98', code: 'IR' },
  { name: 'Iraq', value: '+964', code: 'IQ' },
  { name: 'Ireland', value: '+353', code: 'IE' },
  { name: 'Israel', value: '+972', code: 'IL' },
  { name: 'Italy', value: '+39', code: 'IT' },
  { name: 'Japan', value: '+81', code: 'JP' },
  { name: 'Jordan', value: '+962', code: 'JO' },
  { name: 'Kazakhstan', value: '+7', code: 'KZ' },
  { name: 'Kenya', value: '+254', code: 'KE' },
  { name: 'Kuwait', value: '+965', code: 'KW' },
  { name: 'Latvia', value: '+371', code: 'LV' },
  { name: 'Lebanon', value: '+961', code: 'LB' },
  { name: 'Lithuania', value: '+370', code: 'LT' },
  { name: 'Luxembourg', value: '+352', code: 'LU' },
  { name: 'Malaysia', value: '+60', code: 'MY' },
  { name: 'Maldives', value: '+960', code: 'MV' },
  { name: 'Malta', value: '+356', code: 'MT' },
  { name: 'Mexico', value: '+52', code: 'MX' },
  { name: 'Monaco', value: '+377', code: 'MC' },
  { name: 'Morocco', value: '+212', code: 'MA' },
  { name: 'Nepal', value: '+977', code: 'NP' },
  { name: 'Netherlands', value: '+31', code: 'NL' },
  { name: 'New Zealand', value: '+64', code: 'NZ' },
  { name: 'Nigeria', value: '+234', code: 'NG' },
  { name: 'Norway', value: '+47', code: 'NO' },
  { name: 'Oman', value: '+968', code: 'OM' },
  { name: 'Pakistan', value: '+92', code: 'PK' },
  { name: 'Peru', value: '+51', code: 'PE' },
  { name: 'Philippines', value: '+63', code: 'PH' },
  { name: 'Poland', value: '+48', code: 'PL' },
  { name: 'Portugal', value: '+351', code: 'PT' },
  { name: 'Qatar', value: '+974', code: 'QA' },
  { name: 'Romania', value: '+40', code: 'RO' },
  { name: 'Russia', value: '+7', code: 'RU' },
  { name: 'Saudi Arabia', value: '+966', code: 'SA' },
  { name: 'Serbia', value: '+381', code: 'RS' },
  { name: 'Singapore', value: '+65', code: 'SG' },
  { name: 'Slovakia', value: '+421', code: 'SK' },
  { name: 'Slovenia', value: '+386', code: 'SI' },
  { name: 'South Africa', value: '+27', code: 'ZA' },
  { name: 'South Korea', value: '+82', code: 'KR' },
  { name: 'Spain', value: '+34', code: 'ES' },
  { name: 'Sri Lanka', value: '+94', code: 'LK' },
  { name: 'Sweden', value: '+46', code: 'SE' },
  { name: 'Switzerland', value: '+41', code: 'CH' },
  { name: 'Syria', value: '+963', code: 'SY' },
  { name: 'Taiwan', value: '+886', code: 'TW' },
  { name: 'Thailand', value: '+66', code: 'TH' },
  { name: 'Turkey', value: '+90', code: 'TR' },
  { name: 'Ukraine', value: '+380', code: 'UA' },
  { name: 'United Arab Emirates', value: '+971', code: 'AE' },
  { name: 'United Kingdom', value: '+44', code: 'GB' },
  { name: 'United States', value: '+1', code: 'US' },
  { name: 'Uruguay', value: '+598', code: 'UY' },
  { name: 'Uzbekistan', value: '+998', code: 'UZ' },
  { name: 'Venezuela', value: '+58', code: 'VE' },
  { name: 'Vietnam', value: '+84', code: 'VN' },
  { name: 'Yemen', value: '+967', code: 'YE' },
  { name: 'Zimbabwe', value: '+263', code: 'ZW' },
  { name: 'Other', value: '', code: 'OTH' },
];

export const DEFAULT_COUNTRY = PHONE_COUNTRIES.find(c => c.code === 'SG')!;
